<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="aq-shuttle-a027889d83f1.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="aq-shuttle-a027889d83f1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

</Project>
